# Generated by Django 6.0.4 on 2026-05-03 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='farmacia',
            unique_together={('nome', 'endereco')},
        ),
    ]
