# Generated by Django 6.0.4 on 2026-05-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0002_alter_farmacia_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='farmacia',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='farmacia',
            constraint=models.UniqueConstraint(fields=('nome', 'endereco'), name='unique_farmacia_endereco'),
        ),
    ]
